version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo_db
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/var/lib/mongo

volumes:
  mongodb_data:
